name: Update Resume

on:
  workflow_dispatch:
  # Schedule updates (each hour)
  schedule: 
    - cron: "5 * * * *"

jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
        
      - name: Download new resume
        run: |
          curl https://raw.githubusercontent.com/egelja/resume/master/main.pdf -o assets/pdf/resume.pdf

      - name: Push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: update resume" || true
          git push || true

